<?php namespace ProcessWire;

class RtfPasterTinyMce extends WireData implements Module {

	public static function getModuleInfo() {
		return [
			"title"			=>	"RTF Paster for TinyMCE",
			"summary"		=>	"Allow pasting of RTF content from the Windows clipboard",
			"version"		=>	"0.0.7",
			"autoload"	=>	"process=ProcessPageEdit"
		];
	}
	
	public function init() {
	}
	
	public function ___install() {
		$mod = $this->modules->get('InputfieldTinyMCE');
		$mod->addPlugin('/site/modules/' . $this->className() . '/plugin/rtfpaster.js');
	}
	
	public function ___uninstall() {
		$mod = $this->modules->get('InputfieldTinyMCE');
		$mod->removePlugin('/site/modules/' . $this->className() . '/plugin/rtfpaster.js');
	}


	
}
